# C++ Pre-commit configuration
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=5000']
      - id: check-merge-conflict

  # C++ formatting and linting (temporarily disabled)
  # - repo: https://github.com/pocc/pre-commit-hooks
  #   rev: v1.3.5
  #   hooks:
  #     - id: clang-format
  #       args: [--style=file]
  #
  #     - id: clang-tidy
  #       args: [-checks=*, --warnings-as-errors=*]
  #
  #     - id: cppcheck
  #       args: [
  #         --enable=all,
  #         --suppress=missingIncludeSystem,
  #         --inline-suppr
  #       ]
